/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_48 (
    input [7:0] a,
    input [7:0] b,
    input [0:0] alufn,
    output reg [7:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] sum;
  
  reg [7:0] xb;
  
  always @* begin
    out = a;
    xb = b ^ {4'h8{alufn}};
    sum = a + xb + alufn;
    z = ~((|sum));
    v = (a[7+0-:1] & xb[7+0-:1] & ~sum[7+0-:1]) | (~a[7+0-:1] & ~xb[7+0-:1] & sum[7+0-:1]);
    n = sum[7+0-:1];
    out = sum;
  end
endmodule
