/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_2 (
    input clk,
    input rst,
    input [63:0] cr,
    output reg [7:0] c,
    output reg [7:0] r
  );
  
  
  
  localparam FLIP = 4'hf;
  
  wire [3-1:0] M_counter_r_value;
  counter_26 counter_r (
    .clk(clk),
    .rst(rst),
    .value(M_counter_r_value)
  );
  
  reg [2:0] whichrow;
  
  integer i;
  
  always @* begin
    r = 8'h00;
    c = 8'hff;
    whichrow = M_counter_r_value;
    r[(whichrow)*1+0-:1] = 1'h1;
    for (i = 1'h0; i <= 3'h7; i = i + 1) begin
      c[(i)*1+0-:1] = ~cr[(i)*8+(3'h7 - whichrow)*1+0-:1];
    end
  end
endmodule
