/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_49 (
    input [7:0] a,
    input [7:0] b,
    input [1:0] alufn,
    output reg [7:0] op
  );
  
  
  
  reg result;
  
  reg z;
  
  reg v;
  
  reg n;
  
  reg test;
  
  wire [8-1:0] M_add_out;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  adder_48 add (
    .alufn(alufn[0+0-:1]),
    .a(a[0+7-:8]),
    .b(b[0+7-:8]),
    .out(M_add_out),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n)
  );
  
  always @* begin
    op = 8'h00;
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
    if (a < b) begin
      test = 1'h1;
    end else begin
      test = 1'h0;
    end
    
    case (alufn[0+1-:2])
      2'h1: begin
        result = z;
      end
      2'h2: begin
        result = test;
      end
      2'h3: begin
        result = z | (n ^ v);
      end
      default: begin
        result = 1'h0;
      end
    endcase
    op[0+0-:1] = result;
  end
endmodule
